[tox]

[testenv]

install_command =
    python -m pip install {opts} {packages}

allowlist_externals =
    bash

[testenv:tests]
usedevelop = True
deps =
    -rrequirements-test.txt
commands =
    pytest -vv --log-level DEBUG \
        --cov src --cov-branch --cov-report html:{envtmpdir}/test_coverage --cov-fail-under 0 \
        --html {envtmpdir}/test_report/index.html



[testenv:build]

skip_install = true

deps =
    build

commands_pre =
    bash  -c "rm -rf '{toxinidir}/dist';"

commands =
    python -m build --sdist --wheel
